sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

localmysql: &localmysql
  adapter: mysql2
  database: "facts"
  username: "root"
  password: "test"
  host:     127.0.0.1
  port:     3306
  pool: 5
  timeout: 5000
  encoding: utf8


default: &default
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>

development:
  <<: *mysql
  #<<: *default
  #database: db/development.sqlite3

test:
  <<: *mysql
  #<<: *default
  #database: db/test.sqlite3

mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  <<: *mysql
