# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a21cc533d6456b2c70083119359ba9a4762bc7781595f57e0c8a2376526eef82c12d4489ac9a942a265fb1d3dfa8231fbefba6ede6a0e50332f619583d7ce41

test:
  secret_key_base: 8cbd08d29eaadd5e63f39d7ac936eddfc89b94335f8d19ed05cf7b6027fb2ebae70ed77122202837ac7fa31164c7131daf022c1d1ddf9fc7c319bd4607c46fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
